version: '3.8'
services:
  mysql:
    image: mysql
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todolist
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: